name: PersonalChest
version: 1.0.1+item_dupe_fix_by_st_remy
main: nl.rodey.personalchest.pchestMain
commands:
   pchest:
      description: Register or unregister the Chest with these commands.
      usage: /pchest [CREATE|REMOVE]